### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DevVigilante** [moderGamer/data#1]
Bro are you creating website for Ghost web editor or response for loading data??
Do you blocked me on telegram OR no longer use telegram?

**Comment by TechnicalStudioDeveloper** [comment]
I am unable to understand your language.

**Comment by DevVigilante** [comment]
![Screenshot_2023-03-08-09-03-05-087_com android chrome](https://user-images.githubusercontent.com/96680248/223612935-83a3d5a9-c3c8-4976-8508-09e1ddf76db2.jpg)
Instead of creating too commits use `git commit --amend`.

**Comment by moderGamer** [comment]
> 

Hello, this data is mandatory for the update. Ninja Coder and I are chatting with the same account because my account was hacked. This is my new ID.
@Injectormain

**Comment by DevVigilante** [comment]
> 

ok
